### PR TITLE
Styling for documents, publications, and impacts on the study page

### LINKED ISSUE #72: Decide how outputs (publications, disseminations, impacts) should be displayed
These weren't included in the static mockups.

We need styles for publications, disseminations, and impacts in the sidebar and in the study timeline.

Note that disseminations and other impacts can have potentially very long descriptions attached to them, so we need a way of exposing the descriptions without getting in the way.

### PR DESCRIPTION
**Pull request by stevenday**
Fixes #72. (Updated and re-opened against the latest version of the study page
by @stevenday)

screen shot 2016-01-29 at 12 48 13

screen shot 2016-01-29 at 12 54 18

Things I'm not sure about, and maybe @kimmwest can offer feedback on:

* Currently, "disseminations" and "other impacts" aren't listed in the sidebar, just because they could potentially be very long/wordy. Is this satisfactory? Or should we work out a way of adding them to the sidebar? (Worth remembering, the sidebar is really only meant to be there for quick access to related documents etc – rather than being just a replication of the timeline beside it.)
* Also, if the text description provided for a "dissemination" or "other impact" is really long, we do nothing to shorten it for display in the timeline. Maybe we might want to cut off after the first paragraph, and add a "Read more…" link to reveal the remainder? How much are we expecting people to write?

### CODE REVIEW

**Comment by stevenday** [comment]
@zarino - I've noticed a couple of issues with this: 

1. The svg icons aren't being scaled like the pngs are (I think) so they get clipped, how do I fix that?
2. Really long file names need to word-break or be clipped - which would you prefer?

screen shot 2016-02-03 at 10 39 32

**Comment by zarino** [comment]
@stevenday You can add to that list:

3. Type inside SVGs needs to be converted to outlines!
4. Needs more vertical spacing between different files.

I'll investigate later this sprint.

**Comment by stevenday** [comment]
Super, thanks!

I've done some rebasing and fixups, as well as adding a few tests of the new stuff, so you'll have to reset your local branch to work on it, but everything should pass ok now :crosses_fingers

**Comment by stevenday** [comment]
Copying client comments here for sake of any confusion:

> Hi Zarino,
> 
> Your approach is great.
> 
> I think from a management side it could be useful to see in the sidebar the number of impacts or disseminations added
> 
> We don't know how much people are going to write. In practice, probably not much, but the more they write the richer the information we get. Agree that a 'read more' link to display extra text after a certain wordcount would be ideal

**Pull request closed without merging**
