### PR TITLE
Wire up timeline of study activity and "most recent action" card

### PR DESCRIPTION
**Pull request by stevenday**
This PR takes a bit of a roundabout route to get there, but is aimed at wiring
up a few more pieces of the study page.

To do this and test it properly I needed to do a few other things first:
- Add admin pages for all of the things people can contribute like documents
- Change the way study stages are tracked, so that they're an enum instead
  of a separate model
- Add some new time formats for displaying things properly
- Start tracking activity on notes as well

Then I could wire up the views necessary to display all the different
activities from the activity log, and create some helpers to make this a bit
simpler.

For #3

I'll add a few screenshots in a mo...

### CODE REVIEW

**Comment by stevenday** [comment]
Here's a couple of screenshots of the timeline, which combined give you one of everything it could contain:

screen shot 2016-01-26 at 16 29 16

screen shot 2016-01-26 at 16 30 50

(Note, there aren't any links yet because there aren't pages for all those different kinds of things to link to).

And here's an example of the "most recent activity" card where I think there might be a slight issue:

screen shot 2016-01-26 at 16 30 55

**Comment by stevenday** [comment]
ping @zarino for some design thoughts (if you have any) ^

**Comment by zarino** [comment]
@stevenday – looks good to me!

You're right, when a title is changed, the yellow box in the top right looks a bit weird. I wonder whether we could just get away with showing only the *new* title when we report a change of title? We could, potentially, show the *original* title at the bottom of the timeline (below "Study created") – extra smarty points if you can show the original title *only* if we know it was later changed ;-)

I would also add a bit of vertical space between the timeline headings and the blockquotes or "read more" links below them. But that's dead quick for me to add.

**Comment by davea** [comment]
This is great, it's an elegant way of tracking changes to models. :+1:

**Pull request merged**
