### PR TITLE
Drop user roles in favour of an is_admin flag

### PR DESCRIPTION
**Pull request by stevenday**
As the commit message says - @davea pointed out that the user roles were an
unnecessary complication, so this PR removes them.

### CODE REVIEW

**Comment by stevenday** [comment]
This should probably be reviewed after #43, because of the specs it changes

**Comment by davea** [comment]
The only commit here not in #43 is 544da4c, is that right? Looks good :+1:

**Comment by stevenday** [comment]
Yeah, I should have pr-ed this onto that branch instead of onto master, I wasn't sure if I'd need any more migrations in #43 so to keep the order I branched off it.

**Comment by stevenday** [comment]
I've rebased, this over master, changed the default to `true` in the migrations and rebuilt the structure.sql to match. I'll let CodeClimate and Travis do their thing, but I think we should be good to go now.

**Pull request merged**
